### ISSUE TITLE
Add Support for Symfony 5

### ISSUE THREAD

**Issue by kingmaker-agm** [ob-ivan/diversitest#17]
The **Symfony** framework was updated to version 5 and the latest version is **v5.4**.

Update the `composer.json` to include those versions.

**Comment by ob-ivan** [comment]
- [x] `Symfony\Component\Process\Process::__construct()` changed from accepting `string|array` to just `array`. This means that `\Ob_Ivan\DiversiTest\DiversiTestCommand::runCommand()` has to call `Process::fromShellCommandline()` once it is supported. → #24
- [x] Twig switched from underscores to namespaces: `Twig_Loader_Array` => `Twig\Loader\Array`. The actual least version of Twig supported is 1.41 (due to whitespace issues with earlier versions), and that version supports namespaces already. So I can just use the namespaced version. → 9f3e215fb5ba4027ea991a889de0aa7eb25332f0

**Comment by ob-ivan** [comment]
Solved via 6b8a3b0b632c989804325af2c8468c578d29ddea.

**Comment by ob-ivan** [comment]
@kingmaker-agm This is now released with version 0.6. Please see if it fits with your use case.
